### ISSUE TITLE
Published code is not backwards compatible to older browsers

### ISSUE THREAD

**Issue by dobesv** [LinusU/crypto-digest-sync#1]
It would be great if this were published with a backwards-compatible version of the code, e.g. run through babel to replace any uses of `const` with `var`.

**Comment by LinusU** [comment]
Sorry for the late reply on this, I normally don't transpile code before publishing to Npm since I don't know what browsers the users of the module wants to target. I think a better solution is that you transpile all your code, to be sure that everything works for the browser that you are targeting.
